# index:
#    path: /
#    controller: App\Controller\IndexController::hello
api_login_check:
  path: /api/login_check
  methods: ['POST']

api_register:
  path: /api/users
  methods: ['POST']

favorite_categories:
  path: /api/favorite_categories
  methods: ['GET']
